### ISSUE TITLE
Weak link?

### ISSUE THREAD

**Issue by steckerhalter** [stef/websphinx-firefox#1]
If I have understood this correctly the weak link would be Firefox: The master password could (for example) be intercepted by an extension and used to get the passwords via the the websphinx extension?

**Comment by stef** [comment]
well, the password is queried outside of firefox, websphinx uses the pinentry tool from gpg. so in theory the master password is never seen by firefox. 

please close this issue if you agree with this answer.

**Comment by steckerhalter** [comment]
thanks. I couldn't make it work yet but then it's fine...

**Comment by stef** [comment]
oh? what doesn't work?

**Comment by stef** [comment]
please open issues against installer or documentation
