### ISSUE TITLE
Nothing happens trying to create/get a pw

### ISSUE THREAD

**Issue by steckerhalter** [stef/websphinx-firefox#2]
I have sphinx working on the cli, oracle started and the json is in place. When I click create -> get password nothing happens. How do I debug it?

**Comment by stef** [comment]
did you set the path in the json file to the path of `which websphinx`?

you can debug using: `about:debugging` in firefox

**Comment by steckerhalter** [comment]
yes, I set the path.

I get these messages:

```
Exception... "Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsIMessageSender.sendAsyncMessage]"  nsresult: "0xc1f30001 (NS_ERROR_NOT_INITIALIZED)"  location: "JS frame :: resource://gre/modules/ExtensionUtils.jsm :: sendAsyncMessage :: line 514"  data: no]
```

and

```
websphinx failed  background.js:40:5
```

when clicking `Get password`

**Comment by stef** [comment]
huh, that looks like a serious error. while i try to figure out what that means. may i ask which version of firefox are you running?

**Comment by stef** [comment]
if you run this test program:

```
#!/usr/bin/env python3

from pwdsphinx import websphinx
websphinx.create({'cmd': 'create', 'site': 'www.example.com', 'name': 'joe', 'rules': 'ulsd', 'size': 0, 'mode': 'test'})
```
does that work?

**Comment by steckerhalter** [comment]
FF 58.0.2 

the test gives:

```json
{"results": "fail"}
```

**Comment by stef** [comment]
uh, that is very strange. i think this might be two separate problems, the one in ffox is maybe unrelated to websphinx not working. are you ok with helping me digging deeper. i'm very grateful to you helping me debug this. you're one of my first users. thanks so much.

**Comment by stef** [comment]
what happens when you execute this:

```
echo -n 'SETTITLE sphinx password prompt\nSETPROMPT sphinx password\ngetpin\n' | pinentry
```

**Comment by steckerhalter** [comment]
```
$ echo -n 'SETTITLE sphinx password prompt\nSETPROMPT sphinx password\ngetpin\n' | pinentry
OK Pleased to meet you
pinentry-gnome3: Assuan processing failed: Incomplete line passed to IPC
```

**Comment by stef** [comment]
oops. i forgot the -e switch, what happens if you do this:
```
echo -e 'SETTITLE sphinx password prompt\nSETPROMPT sphinx password\ngetpin' | pinentry
```

**Comment by steckerhalter** [comment]
seems to work ok:

```
$ echo -e 'SETTITLE sphinx password prompt\nSETPROMPT sphinx password\ngetpin' | pinentry
OK Pleased to meet you
OK
OK
D bang
OK
```

**Comment by stef** [comment]
hmmm. do you have also `pinentry-gtk-2` installed? or is this missing on your system? if you have it installed, could you try out this:

```
#!/usr/bin/env python3

import subprocess, platform, os

try:
    from pwdsphinx.sphinx import datadir, SphinxHandler
except ImportError:
    from sphinx import datadir, SphinxHandler

if platform.system() == 'Windows':
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    pinentry=os.path.join(BASE_DIR,'pinentry-qt.exe')
else:
    pinentry='pinentry-gtk-2'

def getpwd(title):
    proc=subprocess.Popen([pinentry, '-g'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = proc.communicate(input=('SETTITLE sphinx %spassword prompt\nSETPROMPT sphinx %spassword\ngetpin\n' % (title,title)).encode())
    if proc.returncode == 0:
        for line in out.split(b'\n'):
            if line.startswith(b"D "): return line[2:]

handler = SphinxHandler(datadir)
pwd=getpwd("")
handler.create(print, pwd, "user", "www.example.com", "ulsd", 0)
```

**Comment by steckerhalter** [comment]
it works and produces a password

**Comment by stef** [comment]
damn, so that works and the test from https://github.com/stef/websphinx-firefox/issues/2#issuecomment-372071043 doesn't. wow, i have to think about this. this is super strange.

**Comment by steckerhalter** [comment]
so just to be sure I ran it again and this time it worked:

```json
{"results": {"mode": "test", "name": "joe", "password": "COZ,`_,<fO48'cD@)HJNv&L2:j]_lFk$;x/kiVkR", "cmd": "create", "site": "www.example.com"}}
```

:man_shrugging:

**Comment by steckerhalter** [comment]
hmm, I think it is because I installed `pinentry-gtk2` which was missing before

**Comment by stef** [comment]
oho? would that mean it also works now in firefox?

**Comment by stef** [comment]
if so, i need to document this better.

**Comment by steckerhalter** [comment]
yeah, now I get the pinentry in FF too. by default only pinentry-gnome3 is installed. couldn't it use that as well? why does it need the gtk2 version?

**Comment by steckerhalter** [comment]
oh, it's because `pinentry-gtk-2` is hardcoded. I guess just using `pinentry` would do the trick?

**Comment by steckerhalter** [comment]
I tried it, with:

```python
    pinentry='pinentry'
```

and the gtk2 version removed it works too, since `pinentry` links to the gnome3 version on Debian

**Comment by stef** [comment]
would you agree to make this a setting in the config file? i think that is the cleanest and best solution to this issue.

**Comment by steckerhalter** [comment]
yeah, sounds good. I would default to `pinentry` since most distros symlink to the correct (installed) binary.

**Comment by stef** [comment]
will do so, and will also update the readmes for the websphinx extensions.

**Comment by stef** [comment]
https://github.com/stef/pwdsphinx/commit/11fe0b66660a86d1f3f9696c5a862c20d177623d,
 https://github.com/stef/websphinx-firefox/commit/2a9017f5abf48b062b1d02e4ab65c2c112b488c7, https://github.com/stef/websphinx-chrom/commit/195bb9b5e18bf34fda5e11b8a10582fc42922923 and https://github.com/stef/winsphinx/commit/d5fa8d7de83a8ac9ccb3c7c883d9db2621e69652
should fix/document this.

if you agree this fixes this issue, please close it.

**Comment by stef** [comment]
btw big thanks for helping out figuring this out!

**Comment by steckerhalter** [comment]
You're welcome. To me it looks like SPHINX is the future of password managers and I'm eager to use the first implementation :smile:
